version: '2'

networks:
    mymicroservice:
    microserviceB-shared:
        driver: bridge

services:

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx_proxy_microserviceB
        ports:
            - "8083:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - mymicroservice

    web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: nginx_microserviceB
        ports:
            - "8084:80"
        volumes:
            - ./:/var/www
        links:
            - app
        environment:
            - "VIRTUAL_HOST=api.microservice-b.test"
        networks:
            - mymicroservice
            - microserviceB-shared

    app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: php_microserviceB
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
        networks:
            - mymicroservice
            - microserviceB-shared

    database:
        image: mysql:8.0
        container_name: mysql_microserviceB
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
            - "MYSQL_DATABASE=microserviceB"
        ports:
            - "33062:3306"
        working_dir: /app
        volumes:
            - ./:/var/www
        networks:
            - mymicroservice

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_microserviceB
        links:
            - database:db
        environment:
            - "PMA_USER=root"
            - "PMA_PASSWORD=123"
            - "PHP_UPLOAD_MAX_FILESIZE=100MB"
            - "VIRTUAL_HOST=pma.microservice-b.test"
        networks:
            - mymicroservice


    cache:
        image: redis:3.0
        container_name: redis_microserviceB
        ports:
            - "63792:6379"
        networks:
            - mymicroservice
